### ISSUE TITLE
localstorage instead of cookies

### ISSUE THREAD

**Issue by fellnerse** [generated-online/generated.online#101]

**Comment by mowolf** [comment]
Also, bzgl regulationen ist das egal ob Cookie oder nicht. Man muss den Banner anzeigen wenn man irgendwas speichert was nicht nur zu der anwendung gehört (z.b. Analytics welches nicht selbstgehosted ist).

Da die cookies in Firefox nicht gehen können wir das austesten, vll auch die decay time runter setzten. Oder iein anderer Bug bzw Firefox default einstellung lässt uns keine Cookies setzten.

**Comment by fellnerse** [comment]
also das mit firefox funktioniert jetzt, habe da nur das cors problem wieder gehabt;

bist du dir sicher wegen regularien zu cookies und local storage?

**Comment by mowolf** [comment]
Jap macht ja sonst keinen Sinn:
https://softwareengineering.stackexchange.com/questions/290566/is-localstorage-under-the-cookie-law

**Comment by mowolf** [comment]
Würde es dann bei Cookies belassen. Warum hatten wir bei Firefox n Cors problem und bei den anderen nicht?

**Comment by fellnerse** [comment]
Jab.
Das lag nur am dev server

**Comment by mowolf** [comment]
ok, dann passt das.
