### ISSUE TITLE
back on fkrefox mobile weird:

### ISSUE THREAD

**Issue by fellnerse** [generated-online/generated.online#111]
Back on /recipe/Id page --> /recipe -> loads new random recipe
So backwards just rederects to a random page
Maybe push and go in router not working?

**Comment by mowolf** [comment]
Komisch, eig sollte das keinen Browser History eintrage hinterlassen. War das jetzt bei dem Neuen PR?

**Comment by fellnerse** [comment]
Ja, aber hab das nicht Cross getestet beim aktuellen stand

**Comment by mowolf** [comment]
sollten wir jetzt nochmal testen
