### ISSUE TITLE
when downloading on mobile only the 2nd image is downloaded

### ISSUE THREAD

**Issue by fellnerse** [generated-online/generated.online#120]

**Comment by mowolf** [comment]
Erlichgesagt brauchen wir auch nur die Vorderseite. Die Rückseite bräuchten wir wenn dann nur die linke seite. So kann man das ja auch nicht drucken.

**Comment by fellnerse** [comment]
doch passt perfekt; hab jetzt ne vorlage, wo man das einfach rein hauen kann

**Comment by fellnerse** [comment]
ist halt so cool wenn leute die postkarte selber haben wollen oder ka; finde das schon gut
