### ISSUE TITLE
Downloaded images should have a border

### ISSUE THREAD

**Issue by fellnerse** [generated-online/generated.online#121]
with a white border it would be easier to place in cewe online 
i had no success with border/outline property on postcard-front/back
also placing it as a child to a parent haveing border/outline did not work
giving the canvas a border did also not work
placing the canvas below a child that has a border works, but now only one postcardpart is loaded as this takes some time

**Comment by mowolf** [comment]
Allerdings kann das Bild bei cewe (zumindest mobile) da auch so einsnappen.

**Comment by fellnerse** [comment]
ja aber nur so behindert; weil die entweder nen weißen rand haben wollen; also das bild kleiner als die karte ist; oder dann snappt es so dass das bild viel größer als die postkarte ist; wenn man jetzt nen weißen rand dazumacht ist es einfach zu positioneniere; bzw nix abgeschnitten, aber nicht extrem wichtig
