### ISSUE TITLE
sharing on WhatsApp should also share image

### ISSUE THREAD

**Issue by fellnerse** [generated-online/generated.online#135]

**Comment by mowolf** [comment]
da brauchen wir das als solcial-media image meta tag:

https://stackoverflow.com/questions/19778620/provide-an-image-for-whatsapp-link-sharing

**Comment by mowolf** [comment]
Nicht sicher welches bild wir da sharen wollen. Da wir ein static image brauchen müssten wir die entweder rendern davor und wo hochladen oder wir nehmen einfach unseren Roboterkoch für alles.

**Comment by fellnerse** [comment]
mhm ich dachte ursprünglich an die postkarten; wir haben ja das canvas eigentlich schon, kann man das nicht mitschicken?
