### ISSUE TITLE
add google analytics to all interesting events

### ISSUE THREAD

**Issue by fellnerse** [generated-online/generated.online#146]
- [x] random recipe
- [x] shared on whatsapp
- [x] voted
- [x] info page
- [x] entered info into postcard
- [x] pressed paypal button?
- [x] conversion to alert "postcard is on the way"

**Comment by mowolf** [comment]
https://firebase.google.com/docs/analytics/events

Brauchen dann auch noch so nen cookie banner...

**Comment by fellnerse** [comment]
gute idee, link ist aber bei mir down
